### ISSUE TITLE
Process exits after submitting a Str input

### ISSUE THREAD

**Issue by celeste-42bit** [celeste-42bit/allTheJazz#2]
Output after inputing a str into the prompt-textfield

```
What is your choice? :
Returned (changing to): Error!
Exception in thread "main" java.lang.NoClassDefFoundError: com/mgnt/utils/TimeUtils
        at main.Main.main(Main.java:26)
Caused by: java.lang.ClassNotFoundException: com.mgnt.utils.TimeUtils
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        ... 1 more

[process exited with code 1]
```

**Comment by celeste-42bit** [comment]
Fixed the issue by removing the Time.sleep function
